name: rt_awesome_snackbar_content
description: Uplift your snackbar experience with various alert messages i.e. success, failure, help or warning with unique UI design.
version: 0.1.4
homepage: https://github.com/pravindodia/rt_awesome_snackbar_content

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter_svg: ^2.0.4
  awesome_snackbar_content: ^0.1.3

  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  assets:
    - assets/
    - assets/types/
